# Spring Application Configuration
spring.application.name=clientflow-backend

# Active Profile
spring.profiles.active=dev

# Server Port
server.port=8080

# Logging Level
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

# Spring Security - JWT Config
security.jwt.secret-key=${JWT_SECRET_KEY:default_super_secret_key_that_is_at_least_256_bits_long_for_hmac_sha_256_algorithm_clientflow}
security.jwt.expiration-time=86400000 # 24 hours in ms

# Firebase Cloud Messaging Config
firebase.config.path=${FIREBASE_CONFIG_PATH:classpath:firebase-service-account.json}

# Cloudinary Storage Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
